package com.bbs.entity;

public class Broad {

	public String toString() {
		return broadName;
	}
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_broad.id
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_broad.broad_name
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	private String broadName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_broad.broad_desc
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	private String broadDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_broad.topic_num
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	private Integer topicNum;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_broad.id
	 * @return  the value of t_broad.id
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_broad.id
	 * @param id  the value for t_broad.id
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_broad.broad_name
	 * @return  the value of t_broad.broad_name
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	public String getBroadName() {
		return broadName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_broad.broad_name
	 * @param broadName  the value for t_broad.broad_name
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	public void setBroadName(String broadName) {
		this.broadName = broadName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_broad.broad_desc
	 * @return  the value of t_broad.broad_desc
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	public String getBroadDesc() {
		return broadDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_broad.broad_desc
	 * @param broadDesc  the value for t_broad.broad_desc
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	public void setBroadDesc(String broadDesc) {
		this.broadDesc = broadDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_broad.topic_num
	 * @return  the value of t_broad.topic_num
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	public Integer getTopicNum() {
		return topicNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_broad.topic_num
	 * @param topicNum  the value for t_broad.topic_num
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	public void setTopicNum(Integer topicNum) {
		this.topicNum = topicNum;
	}
}