package com.bbs.entity;

import org.springframework.security.core.GrantedAuthority;

public class Permission implements GrantedAuthority {
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_permission.id
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_permission.perm_name
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	private String permName;
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_permission.id
	 * @return  the value of t_permission.id
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	public Integer getId() {
		return id;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_permission.id
	 * @param id  the value for t_permission.id
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_permission.perm_name
	 * @return  the value of t_permission.perm_name
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	public String getPermName() {
		return permName;
	}
	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_permission.perm_name
	 * @param permName  the value for t_permission.perm_name
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	public void setPermName(String permName) {
		this.permName = permName;
	}
	public String toString() {
		return permName;
	}
    public String getAuthority() {
		// TODO Auto-generated method stub
		return this.permName;
	}
}