package com.bbs.entity;

import java.util.Date;

public class Post {
	
	public String toString() {
		return content;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_post.id
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_post.content
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_post.user_id
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_post.topic_id
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	private Long topicId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_post.post_type
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	private Integer postType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_post.reply_post_id
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	private Long replyPostId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_post.create_time
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	private Date createTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_post.id
	 * @return  the value of t_post.id
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_post.id
	 * @param id  the value for t_post.id
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_post.content
	 * @return  the value of t_post.content
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_post.content
	 * @param content  the value for t_post.content
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_post.user_id
	 * @return  the value of t_post.user_id
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_post.user_id
	 * @param userId  the value for t_post.user_id
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_post.topic_id
	 * @return  the value of t_post.topic_id
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	public Long getTopicId() {
		return topicId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_post.topic_id
	 * @param topicId  the value for t_post.topic_id
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	public void setTopicId(Long topicId) {
		this.topicId = topicId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_post.post_type
	 * @return  the value of t_post.post_type
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	public Integer getPostType() {
		return postType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_post.post_type
	 * @param postType  the value for t_post.post_type
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	public void setPostType(Integer postType) {
		this.postType = postType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_post.reply_post_id
	 * @return  the value of t_post.reply_post_id
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	public Long getReplyPostId() {
		return replyPostId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_post.reply_post_id
	 * @param replyPostId  the value for t_post.reply_post_id
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	public void setReplyPostId(Long replyPostId) {
		this.replyPostId = replyPostId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_post.create_time
	 * @return  the value of t_post.create_time
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_post.create_time
	 * @param createTime  the value for t_post.create_time
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}