package com.bbs.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import com.bbs.enuma.PostType;

public class PostExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_post
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_post
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_post
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_post
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	public PostExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_post
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_post
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_post
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_post
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_post
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_post
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_post
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_post
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_post
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_post
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_post
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> postTypeCriteria;
		protected List<Criterion> allCriteria;
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
			postTypeCriteria = new ArrayList<Criterion>();
		}

		public List<Criterion> getPostTypeCriteria() {
			return postTypeCriteria;
		}

		protected void addPostTypeCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			postTypeCriteria.add(new Criterion(condition, value, "org.apache.ibatis.type.EnumOrdinalTypeHandler"));
			allCriteria = null;
		}

		protected void addPostTypeCriterion(String condition, PostType value1, PostType value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			postTypeCriteria
					.add(new Criterion(condition, value1, value2, "org.apache.ibatis.type.EnumOrdinalTypeHandler"));
			allCriteria = null;
		}

		public boolean isValid() {
			return criteria.size() > 0 || postTypeCriteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			if (allCriteria == null) {
				allCriteria = new ArrayList<Criterion>();
				allCriteria.addAll(criteria);
				allCriteria.addAll(postTypeCriteria);
			}
			return allCriteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
			allCriteria = null;
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
			allCriteria = null;
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
			allCriteria = null;
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andContentIsNull() {
			addCriterion("content is null");
			return (Criteria) this;
		}

		public Criteria andContentIsNotNull() {
			addCriterion("content is not null");
			return (Criteria) this;
		}

		public Criteria andContentEqualTo(String value) {
			addCriterion("content =", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotEqualTo(String value) {
			addCriterion("content <>", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentGreaterThan(String value) {
			addCriterion("content >", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentGreaterThanOrEqualTo(String value) {
			addCriterion("content >=", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLessThan(String value) {
			addCriterion("content <", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLessThanOrEqualTo(String value) {
			addCriterion("content <=", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLike(String value) {
			addCriterion("content like", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotLike(String value) {
			addCriterion("content not like", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentIn(List<String> values) {
			addCriterion("content in", values, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotIn(List<String> values) {
			addCriterion("content not in", values, "content");
			return (Criteria) this;
		}

		public Criteria andContentBetween(String value1, String value2) {
			addCriterion("content between", value1, value2, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotBetween(String value1, String value2) {
			addCriterion("content not between", value1, value2, "content");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(Long value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(Long value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(Long value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(Long value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Long value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<Long> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<Long> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(Long value1, Long value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(Long value1, Long value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andTopicIdIsNull() {
			addCriterion("topic_id is null");
			return (Criteria) this;
		}

		public Criteria andTopicIdIsNotNull() {
			addCriterion("topic_id is not null");
			return (Criteria) this;
		}

		public Criteria andTopicIdEqualTo(Long value) {
			addCriterion("topic_id =", value, "topicId");
			return (Criteria) this;
		}

		public Criteria andTopicIdNotEqualTo(Long value) {
			addCriterion("topic_id <>", value, "topicId");
			return (Criteria) this;
		}

		public Criteria andTopicIdGreaterThan(Long value) {
			addCriterion("topic_id >", value, "topicId");
			return (Criteria) this;
		}

		public Criteria andTopicIdGreaterThanOrEqualTo(Long value) {
			addCriterion("topic_id >=", value, "topicId");
			return (Criteria) this;
		}

		public Criteria andTopicIdLessThan(Long value) {
			addCriterion("topic_id <", value, "topicId");
			return (Criteria) this;
		}

		public Criteria andTopicIdLessThanOrEqualTo(Long value) {
			addCriterion("topic_id <=", value, "topicId");
			return (Criteria) this;
		}

		public Criteria andTopicIdIn(List<Long> values) {
			addCriterion("topic_id in", values, "topicId");
			return (Criteria) this;
		}

		public Criteria andTopicIdNotIn(List<Long> values) {
			addCriterion("topic_id not in", values, "topicId");
			return (Criteria) this;
		}

		public Criteria andTopicIdBetween(Long value1, Long value2) {
			addCriterion("topic_id between", value1, value2, "topicId");
			return (Criteria) this;
		}

		public Criteria andTopicIdNotBetween(Long value1, Long value2) {
			addCriterion("topic_id not between", value1, value2, "topicId");
			return (Criteria) this;
		}

		public Criteria andPostTypeIsNull() {
			addCriterion("post_type is null");
			return (Criteria) this;
		}

		public Criteria andPostTypeIsNotNull() {
			addCriterion("post_type is not null");
			return (Criteria) this;
		}

		public Criteria andPostTypeEqualTo(PostType value) {
			addPostTypeCriterion("post_type =", value, "postType");
			return (Criteria) this;
		}

		public Criteria andPostTypeNotEqualTo(PostType value) {
			addPostTypeCriterion("post_type <>", value, "postType");
			return (Criteria) this;
		}

		public Criteria andPostTypeGreaterThan(PostType value) {
			addPostTypeCriterion("post_type >", value, "postType");
			return (Criteria) this;
		}

		public Criteria andPostTypeGreaterThanOrEqualTo(PostType value) {
			addPostTypeCriterion("post_type >=", value, "postType");
			return (Criteria) this;
		}

		public Criteria andPostTypeLessThan(PostType value) {
			addPostTypeCriterion("post_type <", value, "postType");
			return (Criteria) this;
		}

		public Criteria andPostTypeLessThanOrEqualTo(PostType value) {
			addPostTypeCriterion("post_type <=", value, "postType");
			return (Criteria) this;
		}

		public Criteria andPostTypeIn(List<PostType> values) {
			addPostTypeCriterion("post_type in", values, "postType");
			return (Criteria) this;
		}

		public Criteria andPostTypeNotIn(List<PostType> values) {
			addPostTypeCriterion("post_type not in", values, "postType");
			return (Criteria) this;
		}

		public Criteria andPostTypeBetween(PostType value1, PostType value2) {
			addPostTypeCriterion("post_type between", value1, value2, "postType");
			return (Criteria) this;
		}

		public Criteria andPostTypeNotBetween(PostType value1, PostType value2) {
			addPostTypeCriterion("post_type not between", value1, value2, "postType");
			return (Criteria) this;
		}

		public Criteria andLikesIsNull() {
			addCriterion("likes is null");
			return (Criteria) this;
		}

		public Criteria andLikesIsNotNull() {
			addCriterion("likes is not null");
			return (Criteria) this;
		}

		public Criteria andLikesEqualTo(Integer value) {
			addCriterion("likes =", value, "likes");
			return (Criteria) this;
		}

		public Criteria andLikesNotEqualTo(Integer value) {
			addCriterion("likes <>", value, "likes");
			return (Criteria) this;
		}

		public Criteria andLikesGreaterThan(Integer value) {
			addCriterion("likes >", value, "likes");
			return (Criteria) this;
		}

		public Criteria andLikesGreaterThanOrEqualTo(Integer value) {
			addCriterion("likes >=", value, "likes");
			return (Criteria) this;
		}

		public Criteria andLikesLessThan(Integer value) {
			addCriterion("likes <", value, "likes");
			return (Criteria) this;
		}

		public Criteria andLikesLessThanOrEqualTo(Integer value) {
			addCriterion("likes <=", value, "likes");
			return (Criteria) this;
		}

		public Criteria andLikesIn(List<Integer> values) {
			addCriterion("likes in", values, "likes");
			return (Criteria) this;
		}

		public Criteria andLikesNotIn(List<Integer> values) {
			addCriterion("likes not in", values, "likes");
			return (Criteria) this;
		}

		public Criteria andLikesBetween(Integer value1, Integer value2) {
			addCriterion("likes between", value1, value2, "likes");
			return (Criteria) this;
		}

		public Criteria andLikesNotBetween(Integer value1, Integer value2) {
			addCriterion("likes not between", value1, value2, "likes");
			return (Criteria) this;
		}

		public Criteria andDownIsNull() {
			addCriterion("down is null");
			return (Criteria) this;
		}

		public Criteria andDownIsNotNull() {
			addCriterion("down is not null");
			return (Criteria) this;
		}

		public Criteria andDownEqualTo(Integer value) {
			addCriterion("down =", value, "down");
			return (Criteria) this;
		}

		public Criteria andDownNotEqualTo(Integer value) {
			addCriterion("down <>", value, "down");
			return (Criteria) this;
		}

		public Criteria andDownGreaterThan(Integer value) {
			addCriterion("down >", value, "down");
			return (Criteria) this;
		}

		public Criteria andDownGreaterThanOrEqualTo(Integer value) {
			addCriterion("down >=", value, "down");
			return (Criteria) this;
		}

		public Criteria andDownLessThan(Integer value) {
			addCriterion("down <", value, "down");
			return (Criteria) this;
		}

		public Criteria andDownLessThanOrEqualTo(Integer value) {
			addCriterion("down <=", value, "down");
			return (Criteria) this;
		}

		public Criteria andDownIn(List<Integer> values) {
			addCriterion("down in", values, "down");
			return (Criteria) this;
		}

		public Criteria andDownNotIn(List<Integer> values) {
			addCriterion("down not in", values, "down");
			return (Criteria) this;
		}

		public Criteria andDownBetween(Integer value1, Integer value2) {
			addCriterion("down between", value1, value2, "down");
			return (Criteria) this;
		}

		public Criteria andDownNotBetween(Integer value1, Integer value2) {
			addCriterion("down not between", value1, value2, "down");
			return (Criteria) this;
		}

		public Criteria andReplyPostIdIsNull() {
			addCriterion("reply_post_id is null");
			return (Criteria) this;
		}

		public Criteria andReplyPostIdIsNotNull() {
			addCriterion("reply_post_id is not null");
			return (Criteria) this;
		}

		public Criteria andReplyPostIdEqualTo(Long value) {
			addCriterion("reply_post_id =", value, "replyPostId");
			return (Criteria) this;
		}

		public Criteria andReplyPostIdNotEqualTo(Long value) {
			addCriterion("reply_post_id <>", value, "replyPostId");
			return (Criteria) this;
		}

		public Criteria andReplyPostIdGreaterThan(Long value) {
			addCriterion("reply_post_id >", value, "replyPostId");
			return (Criteria) this;
		}

		public Criteria andReplyPostIdGreaterThanOrEqualTo(Long value) {
			addCriterion("reply_post_id >=", value, "replyPostId");
			return (Criteria) this;
		}

		public Criteria andReplyPostIdLessThan(Long value) {
			addCriterion("reply_post_id <", value, "replyPostId");
			return (Criteria) this;
		}

		public Criteria andReplyPostIdLessThanOrEqualTo(Long value) {
			addCriterion("reply_post_id <=", value, "replyPostId");
			return (Criteria) this;
		}

		public Criteria andReplyPostIdIn(List<Long> values) {
			addCriterion("reply_post_id in", values, "replyPostId");
			return (Criteria) this;
		}

		public Criteria andReplyPostIdNotIn(List<Long> values) {
			addCriterion("reply_post_id not in", values, "replyPostId");
			return (Criteria) this;
		}

		public Criteria andReplyPostIdBetween(Long value1, Long value2) {
			addCriterion("reply_post_id between", value1, value2, "replyPostId");
			return (Criteria) this;
		}

		public Criteria andReplyPostIdNotBetween(Long value1, Long value2) {
			addCriterion("reply_post_id not between", value1, value2, "replyPostId");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2, "createTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_post
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_post
     *
     * @mbg.generated do_not_delete_during_merge Fri May 04 01:01:21 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}