package com.bbs.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TopicExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_topic
	 * @mbg.generated  Fri May 04 01:33:06 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_topic
	 * @mbg.generated  Fri May 04 01:33:06 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_topic
	 * @mbg.generated  Fri May 04 01:33:06 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_topic
	 * @mbg.generated  Fri May 04 01:33:06 CST 2018
	 */
	public TopicExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_topic
	 * @mbg.generated  Fri May 04 01:33:06 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_topic
	 * @mbg.generated  Fri May 04 01:33:06 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_topic
	 * @mbg.generated  Fri May 04 01:33:06 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_topic
	 * @mbg.generated  Fri May 04 01:33:06 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_topic
	 * @mbg.generated  Fri May 04 01:33:06 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_topic
	 * @mbg.generated  Fri May 04 01:33:06 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_topic
	 * @mbg.generated  Fri May 04 01:33:06 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_topic
	 * @mbg.generated  Fri May 04 01:33:06 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_topic
	 * @mbg.generated  Fri May 04 01:33:06 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_topic
	 * @mbg.generated  Fri May 04 01:33:06 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_topic
	 * @mbg.generated  Fri May 04 01:33:06 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andBroadIdIsNull() {
			addCriterion("broad_id is null");
			return (Criteria) this;
		}

		public Criteria andBroadIdIsNotNull() {
			addCriterion("broad_id is not null");
			return (Criteria) this;
		}

		public Criteria andBroadIdEqualTo(Integer value) {
			addCriterion("broad_id =", value, "broadId");
			return (Criteria) this;
		}

		public Criteria andBroadIdNotEqualTo(Integer value) {
			addCriterion("broad_id <>", value, "broadId");
			return (Criteria) this;
		}

		public Criteria andBroadIdGreaterThan(Integer value) {
			addCriterion("broad_id >", value, "broadId");
			return (Criteria) this;
		}

		public Criteria andBroadIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("broad_id >=", value, "broadId");
			return (Criteria) this;
		}

		public Criteria andBroadIdLessThan(Integer value) {
			addCriterion("broad_id <", value, "broadId");
			return (Criteria) this;
		}

		public Criteria andBroadIdLessThanOrEqualTo(Integer value) {
			addCriterion("broad_id <=", value, "broadId");
			return (Criteria) this;
		}

		public Criteria andBroadIdIn(List<Integer> values) {
			addCriterion("broad_id in", values, "broadId");
			return (Criteria) this;
		}

		public Criteria andBroadIdNotIn(List<Integer> values) {
			addCriterion("broad_id not in", values, "broadId");
			return (Criteria) this;
		}

		public Criteria andBroadIdBetween(Integer value1, Integer value2) {
			addCriterion("broad_id between", value1, value2, "broadId");
			return (Criteria) this;
		}

		public Criteria andBroadIdNotBetween(Integer value1, Integer value2) {
			addCriterion("broad_id not between", value1, value2, "broadId");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(Long value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(Long value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(Long value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(Long value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Long value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<Long> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<Long> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(Long value1, Long value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(Long value1, Long value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andTitleIsNull() {
			addCriterion("title is null");
			return (Criteria) this;
		}

		public Criteria andTitleIsNotNull() {
			addCriterion("title is not null");
			return (Criteria) this;
		}

		public Criteria andTitleEqualTo(String value) {
			addCriterion("title =", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotEqualTo(String value) {
			addCriterion("title <>", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThan(String value) {
			addCriterion("title >", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThanOrEqualTo(String value) {
			addCriterion("title >=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThan(String value) {
			addCriterion("title <", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThanOrEqualTo(String value) {
			addCriterion("title <=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLike(String value) {
			addCriterion("title like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotLike(String value) {
			addCriterion("title not like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleIn(List<String> values) {
			addCriterion("title in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotIn(List<String> values) {
			addCriterion("title not in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleBetween(String value1, String value2) {
			addCriterion("title between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotBetween(String value1, String value2) {
			addCriterion("title not between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andViewsIsNull() {
			addCriterion("views is null");
			return (Criteria) this;
		}

		public Criteria andViewsIsNotNull() {
			addCriterion("views is not null");
			return (Criteria) this;
		}

		public Criteria andViewsEqualTo(Integer value) {
			addCriterion("views =", value, "views");
			return (Criteria) this;
		}

		public Criteria andViewsNotEqualTo(Integer value) {
			addCriterion("views <>", value, "views");
			return (Criteria) this;
		}

		public Criteria andViewsGreaterThan(Integer value) {
			addCriterion("views >", value, "views");
			return (Criteria) this;
		}

		public Criteria andViewsGreaterThanOrEqualTo(Integer value) {
			addCriterion("views >=", value, "views");
			return (Criteria) this;
		}

		public Criteria andViewsLessThan(Integer value) {
			addCriterion("views <", value, "views");
			return (Criteria) this;
		}

		public Criteria andViewsLessThanOrEqualTo(Integer value) {
			addCriterion("views <=", value, "views");
			return (Criteria) this;
		}

		public Criteria andViewsIn(List<Integer> values) {
			addCriterion("views in", values, "views");
			return (Criteria) this;
		}

		public Criteria andViewsNotIn(List<Integer> values) {
			addCriterion("views not in", values, "views");
			return (Criteria) this;
		}

		public Criteria andViewsBetween(Integer value1, Integer value2) {
			addCriterion("views between", value1, value2, "views");
			return (Criteria) this;
		}

		public Criteria andViewsNotBetween(Integer value1, Integer value2) {
			addCriterion("views not between", value1, value2, "views");
			return (Criteria) this;
		}

		public Criteria andLastPostIsNull() {
			addCriterion("last_post is null");
			return (Criteria) this;
		}

		public Criteria andLastPostIsNotNull() {
			addCriterion("last_post is not null");
			return (Criteria) this;
		}

		public Criteria andLastPostEqualTo(Date value) {
			addCriterion("last_post =", value, "lastPost");
			return (Criteria) this;
		}

		public Criteria andLastPostNotEqualTo(Date value) {
			addCriterion("last_post <>", value, "lastPost");
			return (Criteria) this;
		}

		public Criteria andLastPostGreaterThan(Date value) {
			addCriterion("last_post >", value, "lastPost");
			return (Criteria) this;
		}

		public Criteria andLastPostGreaterThanOrEqualTo(Date value) {
			addCriterion("last_post >=", value, "lastPost");
			return (Criteria) this;
		}

		public Criteria andLastPostLessThan(Date value) {
			addCriterion("last_post <", value, "lastPost");
			return (Criteria) this;
		}

		public Criteria andLastPostLessThanOrEqualTo(Date value) {
			addCriterion("last_post <=", value, "lastPost");
			return (Criteria) this;
		}

		public Criteria andLastPostIn(List<Date> values) {
			addCriterion("last_post in", values, "lastPost");
			return (Criteria) this;
		}

		public Criteria andLastPostNotIn(List<Date> values) {
			addCriterion("last_post not in", values, "lastPost");
			return (Criteria) this;
		}

		public Criteria andLastPostBetween(Date value1, Date value2) {
			addCriterion("last_post between", value1, value2, "lastPost");
			return (Criteria) this;
		}

		public Criteria andLastPostNotBetween(Date value1, Date value2) {
			addCriterion("last_post not between", value1, value2, "lastPost");
			return (Criteria) this;
		}

		public Criteria andRepliesIsNull() {
			addCriterion("replies is null");
			return (Criteria) this;
		}

		public Criteria andRepliesIsNotNull() {
			addCriterion("replies is not null");
			return (Criteria) this;
		}

		public Criteria andRepliesEqualTo(Integer value) {
			addCriterion("replies =", value, "replies");
			return (Criteria) this;
		}

		public Criteria andRepliesNotEqualTo(Integer value) {
			addCriterion("replies <>", value, "replies");
			return (Criteria) this;
		}

		public Criteria andRepliesGreaterThan(Integer value) {
			addCriterion("replies >", value, "replies");
			return (Criteria) this;
		}

		public Criteria andRepliesGreaterThanOrEqualTo(Integer value) {
			addCriterion("replies >=", value, "replies");
			return (Criteria) this;
		}

		public Criteria andRepliesLessThan(Integer value) {
			addCriterion("replies <", value, "replies");
			return (Criteria) this;
		}

		public Criteria andRepliesLessThanOrEqualTo(Integer value) {
			addCriterion("replies <=", value, "replies");
			return (Criteria) this;
		}

		public Criteria andRepliesIn(List<Integer> values) {
			addCriterion("replies in", values, "replies");
			return (Criteria) this;
		}

		public Criteria andRepliesNotIn(List<Integer> values) {
			addCriterion("replies not in", values, "replies");
			return (Criteria) this;
		}

		public Criteria andRepliesBetween(Integer value1, Integer value2) {
			addCriterion("replies between", value1, value2, "replies");
			return (Criteria) this;
		}

		public Criteria andRepliesNotBetween(Integer value1, Integer value2) {
			addCriterion("replies not between", value1, value2, "replies");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_topic
	 * @mbg.generated  Fri May 04 01:33:06 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_topic
     *
     * @mbg.generated do_not_delete_during_merge Fri May 04 01:01:21 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}