package com.bbs.entity;

public class User {
	public String toString() {
		return username;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.id
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.username
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.password
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.credit
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	private Integer credit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.lock_type
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	private Byte lockType;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.id
	 * @return  the value of t_user.id
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.id
	 * @param id  the value for t_user.id
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.username
	 * @return  the value of t_user.username
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.username
	 * @param username  the value for t_user.username
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.password
	 * @return  the value of t_user.password
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.password
	 * @param password  the value for t_user.password
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.credit
	 * @return  the value of t_user.credit
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	public Integer getCredit() {
		return credit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.credit
	 * @param credit  the value for t_user.credit
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	public void setCredit(Integer credit) {
		this.credit = credit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.lock_type
	 * @return  the value of t_user.lock_type
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	public Byte getLockType() {
		return lockType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.lock_type
	 * @param lockType  the value for t_user.lock_type
	 * @mbg.generated  Fri May 04 21:38:44 CST 2018
	 */
	public void setLockType(Byte lockType) {
		this.lockType = lockType;
	}
}