package com.bbs.mapper;

import com.bbs.entity.Broad;
import com.bbs.entity.BroadExample;
import com.bbs.entity.Topic;
import com.bbs.entity.User;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BroadMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_broad
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	long countByExample(BroadExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_broad
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	int deleteByExample(BroadExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_broad
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_broad
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	int insert(Broad record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_broad
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	int insertSelective(Broad record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_broad
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	List<Broad> selectByExample(BroadExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_broad
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	Broad selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_broad
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	int updateByExampleSelective(@Param("record") Broad record, @Param("example") BroadExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_broad
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	int updateByExample(@Param("record") Broad record, @Param("example") BroadExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_broad
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	int updateByPrimaryKeySelective(Broad record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_broad
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	int updateByPrimaryKey(Broad record);

	/*
	 * 自定义内容
	 * 
	 * */
	int deleteByName(String broadName);
	
	List<Broad> selectAllBroad();
	
	List<Broad> queryAllBroadLikeName(String broadName);
	
	int addBroadManagerByBroadIdAndUserId(@Param("broadId") int broadId, @Param("userId") long userId);
	
	int deleteBroadManager(@Param("broadId") int broadId, @Param("userId") long userId);
	
	List<User> selectAllBroadManager();
	
	int deteleAllBroadManager();
	
	List<Topic> selectPagedTopicsByBroadId(int broadId);
}