package com.bbs.mapper;

import com.bbs.entity.Broad;
import com.bbs.entity.BroadExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BroadMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_broad
	 * @mbg.generated  Fri May 04 01:33:06 CST 2018
	 */
	long countByExample(BroadExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_broad
	 * @mbg.generated  Fri May 04 01:33:06 CST 2018
	 */
	int deleteByExample(BroadExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_broad
	 * @mbg.generated  Fri May 04 01:33:06 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_broad
	 * @mbg.generated  Fri May 04 01:33:06 CST 2018
	 */
	int insert(Broad record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_broad
	 * @mbg.generated  Fri May 04 01:33:06 CST 2018
	 */
	int insertSelective(Broad record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_broad
	 * @mbg.generated  Fri May 04 01:33:06 CST 2018
	 */
	List<Broad> selectByExample(BroadExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_broad
	 * @mbg.generated  Fri May 04 01:33:06 CST 2018
	 */
	Broad selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_broad
	 * @mbg.generated  Fri May 04 01:33:06 CST 2018
	 */
	int updateByExampleSelective(@Param("record") Broad record, @Param("example") BroadExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_broad
	 * @mbg.generated  Fri May 04 01:33:06 CST 2018
	 */
	int updateByExample(@Param("record") Broad record, @Param("example") BroadExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_broad
	 * @mbg.generated  Fri May 04 01:33:06 CST 2018
	 */
	int updateByPrimaryKeySelective(Broad record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_broad
	 * @mbg.generated  Fri May 04 01:33:06 CST 2018
	 */
	int updateByPrimaryKey(Broad record);
}