package com.bbs.mapper;

import com.bbs.entity.Permission;
import com.bbs.entity.PermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.security.core.GrantedAuthority;

public interface PermissionMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_permission
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	long countByExample(PermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_permission
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	int deleteByExample(PermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_permission
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_permission
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	int insert(Permission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_permission
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	int insertSelective(Permission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_permission
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	List<Permission> selectByExample(PermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_permission
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	Permission selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_permission
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	int updateByExampleSelective(@Param("record") Permission record, @Param("example") PermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_permission
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	int updateByExample(@Param("record") Permission record, @Param("example") PermissionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_permission
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	int updateByPrimaryKeySelective(Permission record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_permission
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	int updateByPrimaryKey(Permission record);

	List<? extends GrantedAuthority> selectAll(@Param("userId") Long userId, @Param("roleId") Integer roleId);
}