package com.bbs.mapper;

import com.bbs.entity.Topic;
import com.bbs.entity.TopicExample;
import com.bbs.vo.VTopic;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface TopicMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_topic
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	long countByExample(TopicExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_topic
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	int deleteByExample(TopicExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_topic
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_topic
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	int insert(Topic record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_topic
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	int insertSelective(Topic record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_topic
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	List<Topic> selectByExample(TopicExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_topic
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	Topic selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_topic
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	int updateByExampleSelective(@Param("record") Topic record, @Param("example") TopicExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_topic
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	int updateByExample(@Param("record") Topic record, @Param("example") TopicExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_topic
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	int updateByPrimaryKeySelective(Topic record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_topic
	 * @mbg.generated  Fri May 11 21:51:15 CST 2018
	 */
	int updateByPrimaryKey(Topic record);

	int deleteByTitle(String title);
	
	List<VTopic> queryPagedVTopics(@Param("title") String title,@Param("pageNo") int pageNo, @Param("pageSize") int pageSize);
	
	List<Topic> selectPagedTopicsByUserId(@Param("userId") long userId, 
			@Param("pageNo") int pageNo, 
			@Param("pageSize") int pageSize);
	
	int makeDigestTopicById(long topicId);
	
	List<VTopic> selectPagedVTopics(@Param("broadId") Integer broadId, @Param("userId") Long userId,
			@Param("pageNo") Integer pageNo, @Param("pageSize") Integer pageSize);
	
	
}